### ISSUE TITLE
4.8.1 crashes with Pagy and Mongoid 

### ISSUE THREAD

**Issue by jonekdahl** [davidcelis/api-pagination#105]
Hi!

A couple of weeks ago we switched to the Pagy backend and it has been working well so far, but upgrading from 4.8.0 to 4.8.1 broke pagination. Here is a stack trace:

```
TypeError: no implicit conversion of Symbol into Integer
    /home/jon/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/mongo-2.5.3/lib/mongo/collection/view/readable.rb:131:in `[]'
    /home/jon/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/mongo-2.5.3/lib/mongo/collection/view/readable.rb:131:in `count'
    /home/jon/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/mongoid-6.4.1/lib/mongoid/contextual/mongo.rb:71:in `block in count'
    /home/jon/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/mongoid-6.4.1/lib/mongoid/contextual/mongo.rb:531:in `try_cache'
    /home/jon/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/mongoid-6.4.1/lib/mongoid/contextual/mongo.rb:71:in `count'
    /home/jon/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/mongoid-6.4.1/lib/mongoid/contextual.rb:20:in `count'
    /home/jon/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/api-pagination-4.8.1/lib/api-pagination.rb:67:in `pagy_from'
    /home/jon/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/api-pagination-4.8.1/lib/api-pagination.rb:56:in `paginate_with_pagy'
    /home/jon/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/api-pagination-4.8.1/lib/api-pagination.rb:13:in `paginate'
    /home/jon/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/api-pagination-4.8.1/lib/rails/pagination.rb:30:in `_paginate_collection'
    /home/jon/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/api-pagination-4.8.1/lib/rails/pagination.rb:12:in `paginate'
```

We're using Mongoid 6.4.1 and the object that we pass to the `paginate` method is a Mongoid::Criteria. It has a count method but it doesn't seem to accept a symbol.

Commit 08d764c740817dbcb8148cd629170fb7bff07d16 looks suspicious.

**Comment by jonekdahl** [comment]
Hi @davidcelis, I get the same error when I run your snippet above.

**Comment by jonekdahl** [comment]
I can make Pagy work by overriding `pagy_get_vars`, using a Mongoid friendly count mechanism instead of [this one](https://github.com/ddnexus/pagy/blob/master/lib/pagy/backend.rb#L19). `pagy_from` still fails though, since it calls `collection.count(:all)` directly.

**Comment by jonekdahl** [comment]
Perhaps if you could delegate to Pagy::Backend, you wouldn't have to call `count` in api-pagination at all?

If that is not possible, can I override the `pagy_from` behavior somehow?

**Comment by jonekdahl** [comment]
I have now worked around this issue by replacing api-pagination with the Pagy [Headers extra](https://ddnexus.github.io/pagy/extras/headers). Since no one else has shown any interest in this, I'll close this issue. Thanks!
