### ISSUE TITLE
It doesn't work with Grape 1.2.1

### ISSUE THREAD

**Issue by majksner** [davidcelis/api-pagination#116]
After upgrading to Grape 1.2.1 pagination stopped worked, reverting back Grape to 1.1.0 solves the problem.

Full stacktrace below:

```
Traceback (most recent call last):
	144: from bin/rails:9:in `<main>'
	143: from /Users/user/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/dependencies.rb:287:in `require'
	142: from /Users/user/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/dependencies.rb:253:in `load_dependency'
	141: from /Users/user/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/dependencies.rb:287:in `block in require'
	140: from /Users/user/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	139: from /Users/user/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	138: from /Users/user/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	137: from /Users/user/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	136: from /Users/user/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	135: from /Users/user/.rvm/gems/ruby-2.5.3/gems/railties-5.2.1.1/lib/rails/commands.rb:18:in `<main>'
	134: from /Users/user/.rvm/gems/ruby-2.5.3/gems/railties-5.2.1.1/lib/rails/command.rb:46:in `invoke'
	133: from /Users/user/.rvm/gems/ruby-2.5.3/gems/railties-5.2.1.1/lib/rails/command/base.rb:65:in `perform'
	132: from /Users/user/.rvm/gems/ruby-2.5.3/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	131: from /Users/user/.rvm/gems/ruby-2.5.3/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	130: from /Users/user/.rvm/gems/ruby-2.5.3/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	129: from /Users/user/.rvm/gems/ruby-2.5.3/gems/railties-5.2.1.1/lib/rails/commands/console/console_command.rb:95:in `perform'
	128: from /Users/user/.rvm/gems/ruby-2.5.3/gems/railties-5.2.1.1/lib/rails/command/actions.rb:18:in `require_application_and_environment!'
	127: from /Users/user/.rvm/gems/ruby-2.5.3/gems/railties-5.2.1.1/lib/rails/application.rb:337:in `require_environment!'
	126: from /Users/user/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/dependencies.rb:287:in `require'
	125: from /Users/user/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/dependencies.rb:253:in `load_dependency'
	124: from /Users/user/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/dependencies.rb:287:in `block in require'
	123: from /Users/user/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	122: from /Users/user/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	121: from /Users/user/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	120: from /Users/user/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	119: from /Users/user/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	118: from /Users/user/Projects/test/config/environment.rb:5:in `<main>'
	117: from /Users/user/.rvm/gems/ruby-2.5.3/gems/railties-5.2.1.1/lib/rails/application.rb:361:in `initialize!'
	116: from /Users/user/.rvm/gems/ruby-2.5.3/gems/railties-5.2.1.1/lib/rails/initializable.rb:60:in `run_initializers'
	115: from /Users/user/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
	114: from /Users/user/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
	113: from /Users/user/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
	112: from /Users/user/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:347:in `call'
	111: from /Users/user/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:347:in `each'
	110: from /Users/user/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
	109: from /Users/user/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
	108: from /Users/user/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	107: from /Users/user/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
	106: from /Users/user/.rvm/gems/ruby-2.5.3/gems/railties-5.2.1.1/lib/rails/initializable.rb:61:in `block in run_initializers'
	105: from /Users/user/.rvm/gems/ruby-2.5.3/gems/railties-5.2.1.1/lib/rails/initializable.rb:32:in `run'
	104: from /Users/user/.rvm/gems/ruby-2.5.3/gems/railties-5.2.1.1/lib/rails/initializable.rb:32:in `instance_exec'
	103: from /Users/user/.rvm/gems/ruby-2.5.3/gems/railties-5.2.1.1/lib/rails/application/finisher.rb:130:in `block in <module:Finisher>'
	102: from /Users/user/.rvm/gems/ruby-2.5.3/gems/railties-5.2.1.1/lib/rails/application/routes_reloader.rb:10:in `execute'
	101: from /Users/user/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/file_update_checker.rb:83:in `execute'
	100: from /Users/user/.rvm/gems/ruby-2.5.3/gems/railties-5.2.1.1/lib/rails/application/routes_reloader.rb:30:in `block in updater'
	 99: from /Users/user/.rvm/gems/ruby-2.5.3/gems/railties-5.2.1.1/lib/rails/application/routes_reloader.rb:20:in `reload!'
	 98: from /Users/user/.rvm/gems/ruby-2.5.3/gems/railties-5.2.1.1/lib/rails/application/routes_reloader.rb:41:in `load_paths'
	 97: from /Users/user/.rvm/gems/ruby-2.5.3/gems/railties-5.2.1.1/lib/rails/application/routes_reloader.rb:41:in `each'
	 96: from /Users/user/.rvm/gems/ruby-2.5.3/gems/railties-5.2.1.1/lib/rails/application/routes_reloader.rb:41:in `block in load_paths'
	 95: from /Users/user/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/dependencies.rb:281:in `load'
	 94: from /Users/user/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/dependencies.rb:253:in `load_dependency'
	 93: from /Users/user/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/dependencies.rb:281:in `block in load'
	 92: from /Users/user/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
	 91: from /Users/user/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
	 90: from /Users/user/Projects/test/config/routes.rb:9:in `<main>'
	 89: from /Users/user/.rvm/gems/ruby-2.5.3/gems/actionpack-5.2.1.1/lib/action_dispatch/routing/route_set.rb:414:in `draw'
	 88: from /Users/user/.rvm/gems/ruby-2.5.3/gems/actionpack-5.2.1.1/lib/action_dispatch/routing/route_set.rb:432:in `eval_block'
	 87: from /Users/user/.rvm/gems/ruby-2.5.3/gems/actionpack-5.2.1.1/lib/action_dispatch/routing/route_set.rb:432:in `instance_exec'
	 86: from /Users/user/Projects/test/config/routes.rb:77:in `block in <main>'
	 85: from /Users/user/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/dependencies.rb:193:in `const_missing'
	 84: from /Users/user/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:57:in `load_missing_constant'
	 83: from /Users/user/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry'
	 82: from /Users/user/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:58:in `block in load_missing_constant'
	 81: from /Users/user/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/dependencies.rb:506:in `load_missing_constant'
	 80: from /Users/user/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:45:in `require_or_load'
	 79: from /Users/user/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry'
	 78: from /Users/user/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:46:in `block in require_or_load'
	 77: from /Users/user/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/dependencies.rb:352:in `require_or_load'
	 76: from /Users/user/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/dependencies.rb:37:in `load_interlock'
	 75: from /Users/user/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/dependencies/interlock.rb:13:in `loading'
	 74: from /Users/user/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
	 73: from /Users/user/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
	 72: from /Users/user/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/dependencies.rb:37:in `block in load_interlock'
	 71: from /Users/user/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/dependencies.rb:369:in `block in require_or_load'
	 70: from /Users/user/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/dependencies.rb:471:in `load_file'
	 69: from /Users/user/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/dependencies.rb:657:in `new_constants_in'
	 68: from /Users/user/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/dependencies.rb:472:in `block in load_file'
	 67: from /Users/user/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
	 66: from /Users/user/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
	 65: from /Users/user/Projects/test/app/api/api.rb:5:in `<main>'
	 64: from /Users/user/Projects/test/app/api/api.rb:7:in `<class:API>'
	 63: from /Users/user/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/dependencies.rb:193:in `const_missing'
	 62: from /Users/user/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:57:in `load_missing_constant'
	 61: from /Users/user/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry'
	 60: from /Users/user/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:58:in `block in load_missing_constant'
	 59: from /Users/user/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/dependencies.rb:506:in `load_missing_constant'
	 58: from /Users/user/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:45:in `require_or_load'
	 57: from /Users/user/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry'
	 56: from /Users/user/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:46:in `block in require_or_load'
	 55: from /Users/user/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/dependencies.rb:352:in `require_or_load'
	 54: from /Users/user/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/dependencies.rb:37:in `load_interlock'
	 53: from /Users/user/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/dependencies/interlock.rb:13:in `loading'
	 52: from /Users/user/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
	 51: from /Users/user/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
	 50: from /Users/user/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/dependencies.rb:37:in `block in load_interlock'
	 49: from /Users/user/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/dependencies.rb:369:in `block in require_or_load'
	 48: from /Users/user/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/dependencies.rb:471:in `load_file'
	 47: from /Users/user/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/dependencies.rb:657:in `new_constants_in'
	 46: from /Users/user/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/dependencies.rb:472:in `block in load_file'
	 45: from /Users/user/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
	 44: from /Users/user/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
	 43: from /Users/user/Projects/test/app/api/v1/base.rb:3:in `<main>'
	 42: from /Users/user/Projects/test/app/api/v1/base.rb:4:in `<module:V1>'
	 41: from /Users/user/Projects/test/app/api/v1/base.rb:8:in `<class:Base>'
	 40: from /Users/user/.rvm/gems/ruby-2.5.3/gems/grape-1.2.1/lib/grape/api.rb:57:in `const_missing'
	 39: from /Users/user/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/dependencies.rb:193:in `const_missing'
	 38: from /Users/user/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:57:in `load_missing_constant'
	 37: from /Users/user/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry'
	 36: from /Users/user/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:58:in `block in load_missing_constant'
	 35: from /Users/user/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/dependencies.rb:538:in `load_missing_constant'
	 34: from /Users/user/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/dependencies.rb:193:in `const_missing'
	 33: from /Users/user/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:57:in `load_missing_constant'
	 32: from /Users/user/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry'
	 31: from /Users/user/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:58:in `block in load_missing_constant'
	 30: from /Users/user/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/dependencies.rb:506:in `load_missing_constant'
	 29: from /Users/user/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:45:in `require_or_load'
	 28: from /Users/user/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry'
	 27: from /Users/user/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:46:in `block in require_or_load'
	 26: from /Users/user/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/dependencies.rb:352:in `require_or_load'
	 25: from /Users/user/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/dependencies.rb:37:in `load_interlock'
	 24: from /Users/user/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/dependencies/interlock.rb:13:in `loading'
	 23: from /Users/user/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
	 22: from /Users/user/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
	 21: from /Users/user/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/dependencies.rb:37:in `block in load_interlock'
	 20: from /Users/user/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/dependencies.rb:369:in `block in require_or_load'
	 19: from /Users/user/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/dependencies.rb:471:in `load_file'
	 18: from /Users/user/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/dependencies.rb:657:in `new_constants_in'
	 17: from /Users/user/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.1.1/lib/active_support/dependencies.rb:472:in `block in load_file'
	 16: from /Users/user/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
	 15: from /Users/user/.rvm/gems/ruby-2.5.3/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
	 14: from /Users/user/Projects/test/app/api/v1/projects_data.rb:6:in `<main>'
	 13: from /Users/user/Projects/test/app/api/v1/projects_data.rb:7:in `<module:V1>'
	 12: from /Users/user/Projects/test/app/api/v1/projects_data.rb:8:in `<class:ProjectsData>'
	 11: from /Users/user/.rvm/gems/ruby-2.5.3/gems/grape-1.2.1/lib/grape/api.rb:36:in `block (2 levels) in override_all_methods!'
	 10: from /Users/user/.rvm/gems/ruby-2.5.3/gems/grape-1.2.1/lib/grape/api.rb:105:in `add_setup'
	  9: from /Users/user/.rvm/gems/ruby-2.5.3/gems/grape-1.2.1/lib/grape/api.rb:105:in `each'
	  8: from /Users/user/.rvm/gems/ruby-2.5.3/gems/grape-1.2.1/lib/grape/api.rb:106:in `block in add_setup'
	  7: from /Users/user/.rvm/gems/ruby-2.5.3/gems/grape-1.2.1/lib/grape/dsl/routing.rb:165:in `namespace'
	  6: from /Users/user/.rvm/gems/ruby-2.5.3/gems/grape-1.2.1/lib/grape/dsl/settings.rb:158:in `within_namespace'
	  5: from /Users/user/.rvm/gems/ruby-2.5.3/gems/grape-1.2.1/lib/grape/dsl/routing.rb:168:in `block in namespace'
	  4: from /Users/user/.rvm/gems/ruby-2.5.3/gems/grape-1.2.1/lib/grape/api/instance.rb:88:in `nest'
	  3: from /Users/user/.rvm/gems/ruby-2.5.3/gems/grape-1.2.1/lib/grape/api/instance.rb:88:in `each'
	  2: from /Users/user/.rvm/gems/ruby-2.5.3/gems/grape-1.2.1/lib/grape/api/instance.rb:88:in `block in nest'
	  1: from /Users/user/.rvm/gems/ruby-2.5.3/gems/grape-1.2.1/lib/grape/api/instance.rb:88:in `instance_eval'
/Users/user/Projects/test/app/api/v1/projects_data.rb:18:in `block in <class:ProjectsData>': undefined method `paginate' for #<Class:0x00007ffd4d858b60> (NoMethodError)
```

**Comment by davidcelis** [comment]
#117 has been merged and I've cut a release with the fix. Try out v4.8.2!
