### ISSUE TITLE
Doesn't work anymore with multi word classes

### ISSUE THREAD

**Issue by adrientoub** [davidcelis/api-pagination#83]
Since the commit 906b09682e7c12d8929004293abe35a3d57f0732 the paginate method returns a LoadError when a class related to a table with an underscore in the name is used.

For instance here the class is called PromotionCode and the code looks for a Promotion_code which is obviously wrong.

```
LoadError:
  Unable to autoload constant Promotion_code, expected .../app/models/promotion_code.rb to define it
# .../api-pagination-4.6.2/lib/api-pagination.rb:85:in `detect_model'
# .../api-pagination-4.6.2/lib/api-pagination.rb:78:in `default_per_page_for_will_paginate'
# .../api-pagination-4.6.2/lib/api-pagination.rb:57:in `paginate_with_will_paginate'
# .../api-pagination-4.6.2/lib/api-pagination.rb:15:in `paginate'
# .../api-pagination-4.6.2/lib/rails/pagination.rb:30:in `_paginate_collection'
# .../api-pagination-4.6.2/lib/rails/pagination.rb:9:in `paginate'
...
```

The line 85 of the code is obviously wrong, this only works for single words class:
```ruby
        collection.table_name.singularize.capitalize.constantize
```

**Comment by davidcelis** [comment]
Fix released in 4.6.3
